spring.application.name=cours_service
spring.datasource.url=jdbc:mysql://mysql-cours_db:3306/cours_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=cours_service
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/